### ISSUE TITLE
I can't use css/style.scss in the index.html

### ISSUE THREAD

**Issue by kaborkhlq** [kaborkhlq/Responsive-Marketplace-UI#1]
In this UI, there is style.scss (scss file) in the css folder.
I updated this file and import in the html using <link> tag
But styles are not applied.

**Comment by unicorndev99** [comment]
Yeah, We can't import scss file in the html.
we can just use css or less file for style in the html.
If you want to convert scss file to css , pls use live-sass-compiler extension in the VS code.
And this extension will generate css file from your scss.

**Comment by kaborkhlq** [comment]
thanks. I see
